[project]
name = "emergency-dashboard"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi>=0.136.1",
    "flask>=3.1.3",
    "flask-cors>=6.0.2",
    "openai>=2.37.0",
    "pandas>=2.3.2",
    "python-dotenv>=1.2.2",
    "requests>=2.34.2",
]
